/* ──────────────────────────────────────────────────
Fresh start
────────────────────────────────────────────────── */
DROP TABLE IF EXISTS invoice_line;

DROP TABLE IF EXISTS invoice;

DROP TABLE IF EXISTS order_line;

DROP TABLE IF EXISTS sales_order;

DROP TABLE IF EXISTS product;

DROP TABLE IF EXISTS client_phone;

DROP TABLE IF EXISTS client;

/* ──────────────────────────────────────────────────
Create tables
────────────────────────────────────────────────── */
CREATE TABLE
    client (
        client_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100) NOT NULL,
        fax_number VARCHAR(30),
        email VARCHAR(255) UNIQUE
    );

CREATE TABLE
    client_phone (
        client_id INTEGER NOT NULL REFERENCES client (client_id) ON DELETE CASCADE,
        phone_no VARCHAR(30) NOT NULL,
        PRIMARY KEY (client_id, phone_no)
    );

CREATE TABLE
    product (
        product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_code INTEGER NOT NULL UNIQUE, -- 1, 2, 3… from the sheet
        product_name TEXT NOT NULL,
        unit_price NUMERIC(10, 2) NOT NULL CHECK (unit_price >= 0)
    );

CREATE TABLE
    sales_order (
        order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_id INTEGER NOT NULL REFERENCES client (client_id) ON DELETE RESTRICT,
        order_date DATE NOT NULL
    );

CREATE TABLE
    order_line (
        order_id INTEGER NOT NULL REFERENCES sales_order (order_id) ON DELETE CASCADE,
        product_id INTEGER NOT NULL REFERENCES product (product_id) ON DELETE RESTRICT,
        quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
        PRIMARY KEY (order_id, product_id)
    );

CREATE TABLE
    invoice (
        invoice_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id INTEGER NOT NULL REFERENCES sales_order (order_id) ON DELETE CASCADE,
        invoice_date DATE NOT NULL,
        payment_date DATE,
        payment_method VARCHAR(40)
    );

CREATE TABLE
    invoice_line (
        invoice_id INTEGER NOT NULL REFERENCES invoice (invoice_id) ON DELETE CASCADE,
        product_id INTEGER NOT NULL REFERENCES product (product_id) ON DELETE RESTRICT,
        quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
        PRIMARY KEY (invoice_id, product_id)
    );

/* ──────────────────────────────────────────────────
Insert data
────────────────────────────────────────────────── */
INSERT INTO
    client (
        client_id,
        first_name,
        last_name,
        fax_number,
        email
    )
VALUES
    (1, 'Helle', 'Jensen', '23456789', 'helle@mail.dk'),
    (
        2,
        'Jens',
        'Christensen',
        '74868745',
        'jens@mail.dk'
    ),
    (3, 'Brian', 'Petersen', NULL, 'brian@mail.dk');

INSERT INTO
    client_phone
VALUES
    (1, '12345678'),
    (1, '87654321'),
    (2, '45456565'),
    (2, '56563232'),
    (2, '45357801'),
    (3, '45678385');

INSERT INTO
    product (product_code, product_name, unit_price)
VALUES
    (1, 'Horse', 40000),
    (2, 'Saddle', 6000),
    (3, 'Horse food', 2000),
    (14, 'Horse home', 10000),
    (6, 'Horze socks', 69),
    (8, 'Horse saddle bag', 299),
    (9, 'Horse multi bag', 19),
    (10, 'Horse backpack', 279);

INSERT INTO
    sales_order (order_id, client_id, order_date)
VALUES
    (1, 1, '2013‑01‑01'),
    (2, 2, '2013‑02‑01'),
    (3, 3, '2013‑02‑10');

INSERT INTO
    order_line
VALUES
    (
        1,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 1
        ),
        1
    ),
    (
        1,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 2
        ),
        1
    ),
    (
        1,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 3
        ),
        1
    ),
    (
        1,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 14
        ),
        1
    ),
    (
        2,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 6
        ),
        1
    ),
    (
        3,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 8
        ),
        1
    ),
    (
        3,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 9
        ),
        1
    ),
    (
        3,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 10
        ),
        1
    );

INSERT INTO
    invoice (
        invoice_id,
        order_id,
        invoice_date,
        payment_method
    )
VALUES
    (1, 1, '2013-01-02', 'CreditCard'),
    (2, 1, '2013-01-08', 'Bank Transfer'),
    (3, 2, '2013-02-09', 'Cash'),
    (4, 3, '2013-02-09', 'Cash'),
    (5, 3, '2013-02-10', 'Bank Transfer'),
    (6, 3, '2013-02-14', 'CreditCard');

INSERT INTO
    invoice_line
VALUES
    (
        1,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 1
        ),
        1
    ),
    (
        1,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 2
        ),
        1
    ),
    (
        2,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 3
        ),
        1
    ),
    (
        2,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 14
        ),
        1
    ),
    (
        3,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 6
        ),
        1
    ),
    (
        4,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 8
        ),
        1
    ),
    (
        5,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 9
        ),
        1
    ),
    (
        6,
        (
            SELECT
                product_id
            FROM
                product
            WHERE
                product_code = 10
        ),
        1
    );

/* ──────────────────────────────────────────────────
Query data
────────────────────────────────────────────────── */
-- Q1: Every order with its customer
SELECT
    o.order_id,
    o.order_date,
    c.first_name || ' ' || c.last_name AS customer,
    COUNT(ol.product_id) AS products_in_order
FROM
    sales_order o
    JOIN client c ON c.client_id = o.client_id
    JOIN order_line ol ON ol.order_id = o.order_id
GROUP BY
    o.order_id,
    o.order_date,
    customer
ORDER BY
    o.order_id;

-- Q2: Outstanding invoices (not yet paid)
SELECT
    i.invoice_id,
    o.order_id,
    c.first_name || ' ' || c.last_name AS customer,
    i.invoice_date,
    i.payment_method
FROM
    invoice i
    JOIN sales_order o ON o.order_id = i.order_id
    JOIN client c ON c.client_id = o.client_id
WHERE
    i.payment_date IS NULL;

-- Q3: Revenue by client
SELECT
    c.first_name || ' ' || c.last_name AS customer,
    SUM(il.quantity * p.unit_price) AS total_spent
FROM
    client c
    JOIN sales_order o USING (client_id)
    JOIN invoice i USING (order_id)
    JOIN invoice_line il USING (invoice_id)
    JOIN product p USING (product_id)
GROUP BY
    customer
ORDER BY
    total_spent DESC;